replicaCount: 2

image:
  repository: ghcr.io/aeyrton/k8s-drain-surge
  pullPolicy: IfNotPresent
  tag: ""

controller:
  drainTaints:
    - key: "karpenter.sh/disrupted"
      effect: "NoSchedule"
    - key: "ToBeDeletedByClusterAutoscaler"
      effect: "NoSchedule"
    - key: "node.kubernetes.io/unschedulable"
      effect: "NoSchedule"
  readinessTimeout: "10m"
  requeueInterval: "5s"
  leaderElect: true
  metricsPort: 8080
  healthPort: 8081

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

priorityClassName: system-cluster-critical

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
  annotations: {}
